### ISSUE TITLE
resp.Body is not closed after return 404

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/go-mod-secrets#145]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
go-mod-secrets/internal/pkg/vault/secrets.go

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
GetSecrets() by valut in `Camera Device Service GetCredentials()`. When the secret path is not exist, valut will return 404 and `resp.Body` will not be closed in getAllKeys().

## 🔥 Exception or Error
<pre><code>

It's a resource leak. The connection won't be re-used, and can remain open in which case the file descriptor won't be freed.
It will prompt `too many open files`
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu Core 20
**EdgeX Version [**REQUIRED**]:**
edgexfoundry v2.1.0-dev.1
go-mod-secrets v2.2.0-dev.6

**Anything else relevant?**
No

**Comment by bnevis-i** [comment]
@gao270615179

Does this fix need to be backported to EdgeX 2.1?

**Comment by gao270615179** [comment]
@bnevis-i 
Yes, this problem occured from EdgeX 2.0 at least.
