### ISSUE TITLE
test target in Makefile should run tests with -race flag

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/go-mod-secrets#22]
To ensure our tests (and to some extent production code) are reliable, we should be running unit tests with the -race argument in the Makefile. Currently, the tests pass with this argument, so only the Makefile needs to be adjusted.

**Comment by brandonforster** [comment]
Per discussion on DevOps WG call on 27 February, this has been rescoped from Geneva to Hanoi so that DevOps can address some underlying build concerns.

**Comment by jpwhitemn** [comment]
DevOps addressed
