### ISSUE TITLE
Fix Vault HealthCheck return 200 status code

### ISSUE THREAD

**Issue by ethan256** [edgexfoundry/go-mod-secrets#236]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
- security-secretstore-setup

 The issue is located in: 

Vault's Standby node returns an HTTP status code of 429 by default during a health check, which will cause the secretstore service to deadlock on init. For more information, please check https://github.com/edgexfoundry/edgex-go/issues/4726

### Is this a regression?

 No.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
- 3.0.0

**Anything else relevant?**

**Comment by bnevis-i** [comment]
Work in progress.  Awaiting dependabot update for go-mod-secrets to v3.1.0-dev.16 or later
