### ISSUE TITLE
Add ServerName in TLSClientConfig

### ISSUE THREAD

**Issue by difince** [edgexfoundry/go-mod-secrets#25]
Currently, I am trying to integrate go-mod-secrets into docker-edgex-mongo repo.
And during my work I realized, that I need to specify  ServerName in the TLSClientConfig in order to be able to make a successful request towards Vault.  
https://github.com/edgexfoundry/go-mod-secrets/blob/1ca18e30c8608982067f69f6bbaa2ad52dd9cc81/pkg/providers/vault/secret_manager.go#L135-L141

```
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs: caCertPool,
				ServerName: "edgex-vault",
			},
		},
	}, nil
```
Without this param I get 
`Get https://0.0.0.0:8200/v1/secret/edgex/dbcredentials/scheduler: x509: cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs`

If I am not in mistake and this param is really needed it supposed to be part of [SecretConfig](https://github.com/edgexfoundry/go-mod-secrets/blob/1ca18e30c8608982067f69f6bbaa2ad52dd9cc81/pkg/providers/vault/config.go#L21) struct

**Comment by bnevis-i** [comment]
Additional information: current edgex-vault certificates have

Subject CN=edgex-vault
SAN: DNS:edgex-vault, DNS:edgex-vault.local

The ServerName parameter is [documented](https://golang.org/pkg/crypto/tls/#Config) as
> ServerName indicates the name of the server requested by the client in order to support virtual hosting. ServerName is only set if the client is using SNI

`https://0.0.0.0:8200/v1/secret` looks suspicious to me.  I am thinking it should be `https:/localhost:8200/v1/secret` or `https://127.0.0.1:8200/v1/secret` or `https://edgex-vault:8200/v1/secret`

Where I am going with this is may be we should instead add DNS:127.0.0.1 or DNS:localhost to the SAN list in Vault's certificate.

**Comment by mkbhanda** [comment]
Bryon, if we go with https://edgex-vault:8200/v1/secret
It looks legitimate but would it also serve us better in a cloud context where the service might not be running on localhost/127.0.0.1/0.0.0.0

**Comment by difince** [comment]
It should be https://edgex-vault:8200/v1/secret

About the alternative solution you propose I to not know ... if it is good to add in SAN list these two DNS:127.0.0.1 or DNS:localhost .

**Comment by bnevis-i** [comment]
> Bryon, if we go with https://edgex-vault:8200/v1/secret   It looks legitimate but would it also serve us better in a cloud context where the service might not be running on localhost/127.0.0.1/0.0.0.0

Snaps share the host's network stack, so in such an environment `localhost` is correct.  It is not possible to use `edgex-vault` all the time.  In this sense, this proposed solution would work because we are explicitly telling the TLS library that no matter what the actual address we are using to connect with, that we expect the server to return an `edgex-vault` certificate.  So if the server was at `https://my-vault-server` you would have to either set `ServerName` to match, or make sure that `my-vault-server` returned an `edgex-vault` certificate (presuming you left `ServerName=edgex-vault`)

**Comment by bnevis-i** [comment]
> if it is good to add in SAN list these two DNS:127.0.0.1 or DNS:localhost .

To be honest I have the same trepidation.
