### ISSUE TITLE
Move Auth Token Loader functionality to go-mod-secrets

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/go-mod-secrets#33]
Migrate the functionality in `edgex-go` within the `authtokenloader` package to `go-mod-secrets`. `go-mod-secrets` is a better home for that functionality since others would be able to leverage the functionality and we can also encapsulate all the configuration properties associated with creating a client.

Please see https://github.com/edgexfoundry/edgex-go/issues/1934 for more details.

**Comment by AnthonyMBonafide** [comment]
This issue was created as per the discussion in PR #1914

https://github.com/edgexfoundry/edgex-go/pull/1914

**Comment by bnevis-i** [comment]
What do you plan to do regarding the FileIoPerformer interface?

**Comment by michaelestrin** [comment]
Superceded by https://github.com/edgexfoundry/edgex-go/issues/2235, https://github.com/edgexfoundry/go-mod-bootstrap/issues/12.

**Comment by tingyuz** [comment]
Close the ticket per Michael's comments.
