### ISSUE TITLE
unable to look up Vault token using SecretConfig BuildURL()

### ISSUE THREAD

**Issue by eno-intel** [edgexfoundry/go-mod-secrets#49]
SecretConfig's BuildURL() currently builds it's URL with the SecretStore.Path configuration property, which specifies the location of the secrets in the secret store (Vault).
https://github.com/edgexfoundry/go-mod-secrets/blob/0d4f7659803186844e8eca22c2bea86290a68f44/pkg/providers/vault/config.go#L40

This is problematic as this method is used to construct the URL for the token lookup-self and renew-self Vault APIs.
https://github.com/edgexfoundry/go-mod-secrets/blob/0d4f7659803186844e8eca22c2bea86290a68f44/pkg/providers/vault/client.go#L151

https://github.com/edgexfoundry/go-mod-secrets/blob/0d4f7659803186844e8eca22c2bea86290a68f44/pkg/providers/vault/client.go#L188

As a result, token lookup fails during the secret client initialization: `msg="unable to create SecretClient: HTTP response with status code 404, message: failed to lookup token"`

BuildURL() needs to be generalized to build a URL for any secret provider API path.

**Comment by eno-intel** [comment]
@AnthonyMBonafide @jim-wang-intel

**Comment by bnevis-i** [comment]
This issue is currently affecting blackbox testing.  Fix in progress.

cc: @cloudxxx8 @cherrycl @jinlinGuan
